Allow different configs per client
idaholab/civet pull request #516
Opened 2021-07-07 23:45 UTC by loganharbour

2021-07-08 17:37 UTC, aeslaughter requested changes

2021-07-08 17:37 UTC, aeslaughter commented on client/INLClient.py
> +            load_modules = self.get_config_modules()[claimed['config']]
What happens if 'config' is not in `claimed` and whatever is not in `get_config_modules`...?

2021-07-08 17:37 UTC, aeslaughter commented on client/INLClient.py
> +            return settings.ENVIRONMENT
I usually do this with `getattr` to avoid the "and" statement

```
if getattr(settings, "ENVIRONMENT", None) is not None:
```

2021-07-08 17:37 UTC, aeslaughter commented on client/INLClient.py
> +        elif hasattr(settings, "PER_CLIENT_ENVIRONMENT") and settings.PER_CLIENT_ENVIRONMENT is not None:
same here and a few other places as well

2021-07-08 17:37 UTC, aeslaughter commented on client/INLClient.py
> +                if type(k) != int or type(v) != dict:
`if not isintances(k, int) or not isinstance(v, dict)):`

2021-07-09 14:49 UTC, aeslaughter submitted a review, later dismissed
Two little changes

2021-07-09 14:49 UTC, aeslaughter commented on client/BaseClient.py
> +        if type(config) is not str:
```suggestion
        if not isinstance(config, str):
```

2021-07-09 14:49 UTC, aeslaughter commented on client/INLClient.py
> +        if type(module) is not str:
```suggestion
        if not isinstance(module, str):
```

2021-07-09 16:41 UTC, rwcarlsen approved these changes

2021-07-09 20:20 UTC, rwcarlsen approved these changes

2021-07-09 20:39 UTC, merged